on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: update submodules
        run: git submodule update --init --recursive
      - run: ls -R
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: 'quartz/package-lock.json'
      - run: npm ci
        working-directory: quartz
      - run: npx quartz build --directory=../
        working-directory: quartz
      - name: Add CNAME
        run: echo "vault.anirudh.foo" > quartz/public/CNAME
      - uses: actions/upload-pages-artifact@v4
        with: { path: quartz/public }

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to gh pages
        id: deployment
        uses:  actions/deploy-pages@v4
