on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: 'quartz/package-lock.json'
      - name: Install packages
        run: npm ci
        working-directory: quartz
      - name: Clean Quartz public
        run: rm -rf quartz/public
      - name: Build Quartz
        working-directory: ./quartz
        run: npx quartz build
      - name: Add CNAME
        run: echo "https://vault.anirudh.foo" > quartz/public/CNAME
      - name: Upload to pages
        uses: actions/upload-pages-artifact@v4
        with: { path: quartz/public }

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to gh pages
        id: deployment
        uses:  actions/deploy-pages@v4
